{% set name = "hugo" %}
{% set version = "0.126.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gohugoio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b7e1f393977bdf6275cf33dfff6d1bcd3bab4895e7302c8fd30f05556b13a6ad

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('go-cgo') }} >=1.20
    - go-licenses

test:
  commands:
    - hugo help

about:
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
  summary: The world's fastest framework for building websites.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
