{% set name = "hugo" %}
{% set version = "0.128.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gohugoio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7ee81aac980c23448d9bbdb387ba61ad3ff80fa13e39e9787ebfab9e8cfa0b60

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('go-cgo') }} >=1.20
    - go-licenses

test:
  commands:
    - hugo help

about:
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
  summary: The world's fastest framework for building websites.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
