{% set name = "hugo" %}
{% set version = "0.123.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gohugoio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3e681c0a3f5d1422e7b26cb996ec53f20481ab4bb24eaf9f1ba0cccf5dde20ac

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses

test:
  commands:
    - hugo help

about:
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
  summary: The world's fastest framework for building websites.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
