{% set name = "hugo" %}
{% set version = "0.125.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gohugoio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c50df060b9c760fc12c503a9ca53ca1daa428766715ae9dda74d6ee1f53bd0e4

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('go-cgo') }} >=1.20
    - go-licenses

test:
  commands:
    - hugo help

about:
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
  summary: The world's fastest framework for building websites.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
